### ISSUE TITLE
Navbar layout glitch

### ISSUE THREAD

**Issue by z0mt3c** [alademann/bootstrap#14]
Didn't have the time to look into yet but there seems to be something wrong with the dropdown navigation compared to the original tbs3:
### original tbs3 example

![real](https://f.cloud.github.com/assets/1782471/1368044/9e279c5e-397b-11e3-9c48-682d2748a6bc.png)
http://getbootstrap.com/examples/navbar-fixed-top/
### sass-bootstrap example

![sass](https://f.cloud.github.com/assets/1782471/1368045/9e3ba460-397b-11e3-9d42-d338c7e523b8.png)
http://alademann.github.io/sass-bootstrap/examples/navbar-fixed-top/

Regards

**Comment by z0mt3c** [comment]
I just looked into the problem and noticed the following - it concerns the following scss code:

``` css
.navbar-nav {
  margin: ($navbar-padding-vertical / 2) -$navbar-padding-horizontal;
}
```

Compared to less:

``` css
.navbar-nav {
  margin: (@navbar-padding-vertical / 2) -@navbar-padding-horizontal;
}
```

No big diff - but in case of scss the result is the following :sunny::

``` css
.navbar-nav {
  margin: -7.5px;
}
```

Again, compared to less:

``` css
.navbar-nav {
  margin: 7.5px -15px;
}
```
